Update main.go
this PR does 2 things:
1) renames XMPP_USER and  XMPP_PW env variables into PROMEXP_XMPP_USER and PROMEXP_XMPP_PASSWORD (so it is more compliant with jitsi naming standards) - we use k8s deployment and this collides with other things
2) solves compilation problems with new versions of FluuxIO/go-xmpp go xmpp library
./main.go:150:3: cannot use promoted field TransportConfiguration.Address in struct literal of type xmpp.Config
./main.go:152:3: unknown field 'Password' in struct literal of type xmpp.Config
./main.go:155:3: cannot use promoted field TransportConfiguration.TLSConfig in struct literal of type xmpp.Config
./main.go:264:31: not enough arguments in call to xmpp.NewClient
        have (xmpp.Config, *xmpp.Router)
        want (xmpp.Config, *xmpp.Router, func(error))

this patch doesnt update any documentation